### ISSUE TITLE
iio_channel_get_modifier and iio_channel_get_type seems to work incorrectly.

### ISSUE THREAD

**Issue by mikexing2018** [analogdevicesinc/libiio#219] opened 2018-11-07 02:33 UTC
In my driver, I have 6 channels.

3 of the 6 channels have IIO_ANGL_VEL as type and IIO_MOD_X, IIO_MOD_Y, IIO_MOD_Z as channel_2 (modifier) respectively.

The other 3 channels are IIO_ACCEL and have IIO_MOD_X, IIO_MOD_Y, IIO_MOD_Z as channel_2 (modifier) respectively.

Using libiio's iio_channel_get_modifier and iio_channel_get_type, I am not getting the correct results:

For the IIO_ACCEL channels, I am getting 3 as type (which is correct), and 0 for all the modifiers (incorrect).
For the IIO_ANGL_VEL channels, I am getting a 12 for channel type (incorrect), and 0 for all the modifiers (incorrect)

Here are my channels inside the .........../scan_elements folder on linux:
in_accel_x_en       in_accel_z_index    in_anglvel_y_type
in_accel_x_index    in_accel_z_type     in_anglvel_z_en
in_accel_x_type     in_anglvel_x_en     in_anglvel_z_index
in_accel_y_en       in_anglvel_x_index  in_anglvel_z_type
in_accel_y_index    in_anglvel_x_type   in_timestamp_en
in_accel_y_type     in_anglvel_y_en     in_timestamp_index
in_accel_z_en       in_anglvel_y_index  in_timestamp_type

**Comment by commodo** [comment] 2018-11-07 07:53
Which device are you using this with ?
We could try to reproduce it locally and see what happens.

**Comment by mikexing2018** [comment] 2018-11-07 07:57
This is an IMU device. For confidentiality purpose, I cannot disclose the exact device.

I think this issue should not be device specific. Maybe there is some general problem with those APIs for getting the channel type and modifier? Has anyone ever tested?

**Comment by commodo** [comment] 2018-11-07 08:07
What version of libiio are you using ?

**Comment by mikexing2018** [comment] 2018-11-07 18:12
@pcercuei Yes. I am using local backend. Here are the sequence that I am doing:
iio_create_local_context()
iio_context_find_device
iio_device_get_channels_count
iio_device_get_channel
iio_device_get_type
iio_device_get_modifier

**Comment by mikexing2018** [comment] 2018-11-07 18:14
@commodo 

https://github.com/analogdevicesinc/libiio/archive/v0.15.tar.gz

**Comment by pcercuei** [comment] 2018-11-07 18:17
Maybe a filename parsing error. What are the IDs of the channels, as reported by iio_info?

**Comment by mikexing2018** [comment] 2018-11-07 18:21
The iio_channel_get_id are returning the following values for the 6 channels:
accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z

seems correct.

**Comment by mikexing2018** [comment] 2018-11-07 19:01
The issue is in iio_channel_init_finalize(). There is string parsing errors there for both channel type and channel modifier. For modifier, I don't know why there is an assumption that the modifier needs to be followed by an underscore. For channel type. it's suppose to break when it finds the right type rather than keep looping.

**Comment by pcercuei** [comment] 2018-11-07 20:38
For the modifier, you're right. The check for the underscore is bogus.

For the type, it should break, but that's not the cause of the problem. The condition for the "continue" right above where chn->type is set looks really wrong; the second && should be a || instead (with proper parenthesis set around it).

**Comment by mhennerich** [comment] 2018-11-07 20:43
@mikexing2018 you have a test case - do you mind sending a Pull Request?

**Comment by mhennerich** [comment] 2018-11-08 09:31
Request for test: 
Can you test the fix in the https://github.com/analogdevicesinc/libiio/tree/rft-issue-219 branch?

**Comment by mikexing2018** [comment] 2018-11-09 05:49
Sure

**Comment by mhennerich** [comment] 2018-11-12 21:47
> Sure

Does it fix it?

**Comment by commodo** [comment] 2018-11-19 08:03
@mikexing2018 
ping

**Comment by mikexing2018** [comment] 2018-11-19 08:21
I don't have access to the testing environment this week. Will need to delay until the week of Dec 26th.

**Comment by commodo** [comment] 2018-11-19 08:30
ok :)
thanks for the feedback;
we can wait

**Comment by mhennerich** [comment] 2018-11-19 18:34
Dec 26th? I don't think we can wait that long. 
The PACKRF has a ADIS16460 type IMU, we should be able to quickly test it there. 
Alex can you take a look?

**Comment by commodo** [comment] 2018-11-20 11:17
Yep
Will take a look

Just need to take a look into some build issues first.

**Comment by mhennerich** [comment] 2018-11-21 08:52
Ok - i did some test using a ADIS16460.
		
```
root@analog:/sys/bus/iio/devices/iio:device4# ls -al
total 0
drwxr-xr-x 6 root root    0 Jan  1  1970 .
drwxr-xr-x 6 root root    0 Jan  1  1970 ..
drwxrwxrwx 2 root root    0 Jan  1  1970 buffer
-rw-rw-rw- 1 root root 4096 Jan  1  1970 dev
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_scale
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_x_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_y_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_z_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_scale
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_x_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_y_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_z_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_offset
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_raw
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_scale
-rw-rw-rw- 1 root root 4096 Jan  1  1970 name
lrwxrwxrwx 1 root root    0 Jan  1  1970 of_node -> ../../../../../../../../firmware/devicetree/base/amba/spi@e0007000/adis16460@0
drwxrwxrwx 2 root root    0 Jan  1  1970 power
-rw-rw-rw- 1 root root 4096 Jan  1  1970 sampling_frequency
drwxrwxrwx 2 root root    0 Jan  1  1970 scan_elements
lrwxrwxrwx 1 root root    0 Jan  1  1970 subsystem -> ../../../../../../../../bus/iio
drwxrwxrwx 2 root root    0 Jan  1  1970 trigger
-rw-rw-rw- 1 root root 4096 Jan  1  1970 uevent
root@analog:/sys/bus/iio/devices/iio:device4# ls -al scan_elements/
total 0
drwxrwxrwx 2 root root    0 Jan  1  1970 .
drwxr-xr-x 6 root root    0 Nov 21 08:12 ..
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_x_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_x_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_x_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_y_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_y_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_y_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_z_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_z_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_accel_z_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_x_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_x_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_x_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_y_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_y_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_y_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_z_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_z_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_anglvel_z_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_temp0_type
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_timestamp_en
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_timestamp_index
-rw-rw-rw- 1 root root 4096 Jan  1  1970 in_timestamp_type

root@analog:/sys/bus/iio/devices/iio:device4/scan_elements# grep "" *
in_accel_x_en:0
in_accel_x_index:3
in_accel_x_type:be:s32/32>>0
in_accel_y_en:0
in_accel_y_index:4
in_accel_y_type:be:s32/32>>0
in_accel_z_en:0
in_accel_z_index:5
in_accel_z_type:be:s32/32>>0
in_anglvel_x_en:0
in_anglvel_x_index:0
in_anglvel_x_type:be:s32/32>>0
in_anglvel_y_en:0
in_anglvel_y_index:1
in_anglvel_y_type:be:s32/32>>0
in_anglvel_z_en:0
in_anglvel_z_index:2
in_anglvel_z_type:be:s32/32>>0
in_temp0_en:0
in_temp0_index:6
in_temp0_type:be:s16/16>>0
in_timestamp_en:0
in_timestamp_index:7
in_timestamp_type:le:s64/64>>0
```

Using this simple patch to iio_info - which adds the type and modifier for each channel:

```
diff --git a/tests/iio_info.c b/tests/iio_info.c
index 338ac38..8ba25d5 100644
--- a/tests/iio_info.c
+++ b/tests/iio_info.c
@@ -343,6 +343,8 @@ int main(int argc, char **argv)
                                printf(")\n");
                        }
 
+                       printf("\t\t\t\ttype=%d, modifier=%d\n",iio_channel_get_type(ch), iio_channel_get_modifier(ch));
+
                        unsigned int nb_attrs = iio_channel_get_attrs_count(ch);
                        if (!nb_attrs)
                                continue;
```

This shows clearly the issue:

```
	iio:device4: adis16460 (buffer capable)
		8 channels found:
			anglvel_x:  (input, index: 0, format: be:S32/32>>0)
				type=12, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: 359648
				attr  1: scale value: 0.000000001
			anglvel_y:  (input, index: 1, format: be:S32/32>>0)
				type=12, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: 241343
				attr  1: scale value: 0.000000001
			anglvel_z:  (input, index: 2, format: be:S32/32>>0)
				type=12, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: -2014048
				attr  1: scale value: 0.000000001
			accel_x:  (input, index: 3, format: be:S32/32>>0)
				type=3, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: -67174400
				attr  1: scale value: 0.000000037
			accel_y:  (input, index: 4, format: be:S32/32>>0)
				type=3, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: 3145727
				attr  1: scale value: 0.000000037
			accel_z:  (input, index: 5, format: be:S32/32>>0)
				type=3, modifier=0
			2 channel-specific attributes found:
				attr  0: raw value: 252182527
				attr  1: scale value: 0.000000037
			temp0:  (input, index: 6, format: be:S16/16>>0)
				type=9, modifier=0
			3 channel-specific attributes found:
				attr  0: offset value: 500
				attr  1: scale value: 50
				attr  2: raw value: 219
			timestamp:  (input, index: 7, format: le:S64/64>>0)
				type=13, modifier=0
		1 device-specific attributes found:
				attr  0: sampling_frequency value: 2048.000000
		1 buffer-specific attributes found:
				attr  0: watermark value: 1
		4 debug attributes found:
				debug attr  0: flash_count value: 157
				debug attr  1: product_id value: 16460
				debug attr  2: serial_number value: 0x09da
				debug attr  3: direct_reg_access value: 0x9D
		Current trigger: trigger0(adis16460-dev4)
```

		
The same with the patch applied, validates the fix:
The modifiers are correct ant also all the types:
Given this, I apply the patch and close this issue. 

```
	iio:device4: adis16460 (buffer capable)
		8 channels found:
			anglvel_x:  (input, index: 0, format: be:S32/32>>0)
				type=4, modifier=1
			2 channel-specific attributes found:
				attr  0: raw value: -1014652
				attr  1: scale value: 0.000000001
			anglvel_y:  (input, index: 1, format: be:S32/32>>0)
				type=4, modifier=2
			2 channel-specific attributes found:
				attr  0: raw value: 635955
				attr  1: scale value: 0.000000001
			anglvel_z:  (input, index: 2, format: be:S32/32>>0)
				type=4, modifier=3
			2 channel-specific attributes found:
				attr  0: raw value: -965408
				attr  1: scale value: 0.000000001
			accel_x:  (input, index: 3, format: be:S32/32>>0)
				type=3, modifier=1
			2 channel-specific attributes found:
				attr  0: raw value: -66453504
				attr  1: scale value: 0.000000037
			accel_y:  (input, index: 4, format: be:S32/32>>0)
				type=3, modifier=2
			2 channel-specific attributes found:
				attr  0: raw value: 4390911
				attr  1: scale value: 0.000000037
			accel_z:  (input, index: 5, format: be:S32/32>>0)
				type=3, modifier=3
			2 channel-specific attributes found:
				attr  0: raw value: 255459327
				attr  1: scale value: 0.000000037
			temp0:  (input, index: 6, format: be:S16/16>>0)
				type=9, modifier=0
			3 channel-specific attributes found:
				attr  0: offset value: 500
				attr  1: scale value: 50
				attr  2: raw value: 227
			timestamp:  (input, index: 7, format: le:S64/64>>0)
				type=2147483647, modifier=0
		1 device-specific attributes found:
				attr  0: sampling_frequency value: 2048.000000
		1 buffer-specific attributes found:
				attr  0: watermark value: 1
		4 debug attributes found:
				debug attr  0: flash_count value: 157
				debug attr  1: product_id value: 16460
				debug attr  2: serial_number value: 0x09da
				debug attr  3: direct_reg_access value: 0x9D
		Current trigger: trigger0(adis16460-dev4)		
```
-Michael

**Closed** 2018-11-21 08:55 UTC
